on: [push]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    name: TfPlan testing
    env:
      TEST_ENV: TEST_ENVIRONMENT_VARIABLE_VALUE
    steps:
      # To use this repository's private action,
      # you must check out the repository      
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: TF Plan
        uses: ./terraform-plan
        id: tfplan
        with:
          path: "../testing/terraform"
          backend_config: |
            "Key1:Value1"
            "Key2:Value2"
          add_github_comment: "true"